
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'EQUALS INT KEYWORD QUOTE STRINGstatement : KEYWORD KEYWORD STRINGstatement : KEYWORD KEYWORD STRING QUOTE STRING QUOTE INTstatement : KEYWORD STRINGstatement : STRING EQUALS INTstatement : STRING EQUALS QUOTE STRING QUOTEstatement : STRING KEYWORD STRING QUOTE STRING QUOTEstatement : STRING KEYWORD STRINGstatement : STRING KEYWORD QUOTE STRING QUOTE KEYWORD INTstatement : STRING KEYWORD QUOTE STRING QUOTEstatement : expressionexpression : INTexpression : KEYWORDexpression : STRING'
    
_lr_action_items = {'KEYWORD':([0,2,3,22,],[2,6,9,25,]),'STRING':([0,2,6,9,12,14,15,17,],[3,7,10,13,16,18,19,21,]),'INT':([0,8,23,25,],[4,11,26,27,]),'$end':([1,2,3,4,5,7,10,11,13,20,22,24,26,27,],[0,-12,-13,-11,-10,-3,-1,-4,-7,-5,-9,-6,-2,-8,]),'EQUALS':([3,],[8,]),'QUOTE':([8,9,10,13,16,18,19,21,],[12,14,15,17,20,22,23,24,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'expression':([0,],[5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> KEYWORD KEYWORD STRING','statement',3,'p_statement_create_or_delete_client_server','lexer.py',46),
  ('statement -> KEYWORD KEYWORD STRING QUOTE STRING QUOTE INT','statement',7,'p_statement_create_server','lexer.py',61),
  ('statement -> KEYWORD STRING','statement',2,'p_statement_info','lexer.py',70),
  ('statement -> STRING EQUALS INT','statement',3,'p_statement_variable_int','lexer.py',77),
  ('statement -> STRING EQUALS QUOTE STRING QUOTE','statement',5,'p_statement_variable_string','lexer.py',82),
  ('statement -> STRING KEYWORD STRING QUOTE STRING QUOTE','statement',6,'p_statement_send_data','lexer.py',87),
  ('statement -> STRING KEYWORD STRING','statement',3,'p_statement_local_conn','lexer.py',94),
  ('statement -> STRING KEYWORD QUOTE STRING QUOTE KEYWORD INT','statement',7,'p_statement_external_conn','lexer.py',101),
  ('statement -> STRING KEYWORD QUOTE STRING QUOTE','statement',5,'p_statement_external_conn_no_port','lexer.py',108),
  ('statement -> expression','statement',1,'p_statement_expr','lexer.py',115),
  ('expression -> INT','expression',1,'p_expression_int','lexer.py',120),
  ('expression -> KEYWORD','expression',1,'p_expression_keyword','lexer.py',125),
  ('expression -> STRING','expression',1,'p_expression_string','lexer.py',130),
]
